
services:
  activemq:
    image: webcenter/activemq:5.14.3
    container_name: activemq
    ports:
      - "8161:8161" 
      - "61616:61616" 
      - "61613:61613"
    environment:
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_ADMIN_USER=admin
    volumes:
      - activemq_data:/var/lib/activemq
      - activemq_conf:/var/lib/activemq/conf
    networks:
      - monitoring_network
    healthcheck: 
      test: ["CMD", "curl", "-f", "-u", "admin:admin", "http://localhost:8161/admin"] 
      interval: 30s 
      timeout: 10s
      retries: 5
      start_period: 20s 

  vehicle_simulator:
    build: 
      context: ./vehicle-iot-simulator
      dockerfile: Dockerfile
    container_name: vehicle_simulator
    ports:
      - 3000:3000
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61613
      - ACTIVEMQ_LOGIN=admin
      - ACTIVEMQ_PASSCODE=admin
    depends_on:
      activemq:
        condition: service_healthy 
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  activemq_data:
    driver: local
  activemq_conf:
    driver: local